site_name: ElreragDocs

nav:
- Home: 'uml/lectura.md'
- UML: 
    - Lectura: 'uml/lectura.md'
    - Quizzes: 'uml/quizzes.md'
    - Desafío 1: 'uml/desafioUno.md'
    - Desafío 2: 'uml/desafioDos.md'

