version: 2.1
description: Orb for firebase deploy.

deploy-job:
  working_directory: /Users/luisherrera/projects/PYTHON/virtual36/env/MKDOCS/desltnDocs
  steps:
    - run:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=1/AIQ24dHJsbBqcN6D40pZc9le-J5gvQIO1_9Nhj0RyJKXZeCdL1_v-ysexPqgqsZa

workflows:
  version: 2
  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master