version: 2

jobs:
  deploy-job:
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp/desltnDocs
    steps:
      - run: npm install -g firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: firebase deploy --token=1/-W52z-gII_i-eYLW6cgIpVLwheiFC3WuArz5mtuE8k5Ue1K_orzrqcWy0qxh8vVM

workflows:
  version: 2
  -deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master
