version: 2

jobs:
  deploy-job:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/desltnDocs
    steps:
      - run: 
          name: Install Firebase Tools
          command: npm install firebase-tools
      - run: ls -l
      - run:
          name: Deploy Master to Firebase
          command: ./tmp/desltnDocs/node_modules/.bin/firebase deploy --token=1/-W52z-gII_i-eYLW6cgIpVLwheiFC3WuArz5mtuE8k5Ue1K_orzrqcWy0qxh8vVM

workflows:
  version: 2
  -deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master
