version: 2

jobs:

  build-job:
    docker:
      - image: circleci/python:3.6
    working_directory: /tmp/desltnDocs
    steps:
      - checkout

      - run: rm -rf site
      - run: 
          name: instalación del virtualenv
          command: pip install --upgrade pip && pip install virtualenv && virtualenv env --python=python3.6
      - run:
          name: instalaciOn de mkdocs y  en un entorno virtual.
          command: source ./env/bin/activate && 
            pip install mkdocs && 
            mkdocs build &&
            ls -l
      - persist_to_workspace:
          root: /tmp/desltnDocs
          paths:
            - site

  deploy-job:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/desltnDocs
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/desltnDocs

      - run: 
          name: Install Firebase Tools
          command: npm install firebase-tools

      - run: ls -l
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=1/-W52z-gII_i-eYLW6cgIpVLwheiFC3WuArz5mtuE8k5Ue1K_orzrqcWy0qxh8vVM

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
