version: 2

jobs:

  build-job:
    docker:
      - image: circleci/python:3.6
    working_directory: /tmp/desltnDocs
    steps:
      - checkout
      - run: rm -rf sites
      - run: 
          name: instalación del virtualenv
          command: pip install --upgrade pip && pip install virtualenv && virtualenv env --python=python3.6
      - run:
          name: instalaciOn de mkdocs y  en un entorno virtual.
          command: source ./env/bin/activate && 
            pip install mkdocs && 
            mkdocs build &&
            ls -l
      - save_cache:
          key: 12345678
          paths:
            - /tmp/desltnDocs/site

  deploy-job:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/desltnDocs
    steps:
      - checkout
      - restore_cache:
          key: 12345678
      - run: 
          name: Install Firebase Tools
          command: npm install firebase-tools
      - run: ls -l
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=1/-W52z-gII_i-eYLW6cgIpVLwheiFC3WuArz5mtuE8k5Ue1K_orzrqcWy0qxh8vVM

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
