version: 2.1
description: Orb for firebase deploy.
commands:
  deploy:
    description: Deploy to firebase
    parameters:
      token:
        type: string
        description: Firebase Deploy Token
    steps:
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase 
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=1/AIQ24dHJsbBqcN6D40pZc9le-J5gvQIO1_9Nhj0RyJKXZeCdL1_v-ysexPqgqsZa